import { config } from '@n8n/node-cli/eslint';

export default [
	...config,
	{
		rules: {
			'@n8n/community-nodes/no-restricted-imports': 'off',
			'@n8n/community-nodes/no-restricted-globals': 'off',
			'@n8n/community-nodes/credential-test-required': 'off',
			'@n8n/community-nodes/credential-password-field': 'off',
			'@n8n/community-nodes/credential-unnecessary-password': 'off',
			'@n8n/community-nodes/no-deprecated-workflow-functions': 'off',
			'@n8n/community-nodes/cred-class-oauth2-naming': 'off',
			'@n8n/community-nodes/require-node-api-error': 'off',
			'@n8n/community-nodes/webhook-lifecycle-complete': 'off',
			'@n8n/community-nodes/icon-prefer-themed-variants': 'off',
			'@n8n/community-nodes/missing-paired-item': 'off',
			'@n8n/community-nodes/no-runtime-dependencies': 'off',
			'@n8n/community-nodes/no-http-request-with-manual-auth': 'off',
			'@n8n/community-nodes/no-hardcoded-secrets': 'off',
			'@n8n/community-nodes/node-connection-type-literal': 'off',
			'@n8n/community-nodes/require-node-description-fields': 'off',
			'n8n-nodes-base/cred-class-field-documentation-url-missing': 'off',
			'n8n-nodes-base/node-param-default-missing': 'off',
			'n8n-nodes-base/node-param-collection-type-unsorted-items': 'off',
			'n8n-nodes-base/node-param-fixed-collection-type-unsorted-items': 'off',
			'n8n-nodes-base/node-param-display-name-wrong-for-dynamic-options': 'off',
			'n8n-nodes-base/node-param-default-wrong-for-options': 'off',
			'n8n-nodes-base/node-param-description-wrong-for-dynamic-options': 'off',
			'n8n-nodes-base/node-param-description-miscased-id': 'off',
			'n8n-nodes-base/node-param-options-type-unsorted-items': 'off',
			'n8n-nodes-base/node-param-description-boolean-without-whether': 'off',
			'n8n-nodes-base/node-param-description-wrong-for-return-all': 'off',
			'n8n-nodes-base/node-param-description-missing-for-return-all': 'off',
			'n8n-nodes-base/node-param-placeholder-missing-email': 'off',
			'n8n-nodes-base/node-param-display-name-miscased': 'off',
			'@typescript-eslint/no-duplicate-enum-values': 'off',
			'no-useless-catch': 'off',
			'@typescript-eslint/no-explicit-any': 'off',
			'@typescript-eslint/no-unused-vars': 'off',
			'@typescript-eslint/ban-ts-comment': 'off',
			'@typescript-eslint/no-require-imports': 'off',
			'@typescript-eslint/no-unsafe-function-type': 'off',
			'prefer-const': 'off',
			'no-console': 'off',
			'import-x/no-duplicates': 'off',
		},
	},
];
